// <auto-generated />
using System;
using ChatWithFriends.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChatWithFriends.Migrations.Safe
{
    [DbContext(typeof(SafeContext))]
    partial class SafeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChatWithFriends.Models.Safe", b =>
                {
                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CupCount")
                        .HasColumnType("int");

                    b.Property<string>("IceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Money")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Money1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Money2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SugarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeaMaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Total")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderTime");

                    b.ToTable("Safes");

                    b.HasData(
                        new
                        {
                            OrderTime = new DateTime(2024, 1, 1, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            CupCount = 1,
                            IceName = "去冰",
                            Money2 = "65",
                            Name = "沉香烏龍那提",
                            OrderName = "弟弟",
                            Shop = "波仕-鮮奶茶系列",
                            SugarName = "半糖",
                            TeaMaterialName = "椰果",
                            Total = "75"
                        },
                        new
                        {
                            OrderTime = new DateTime(2024, 2, 13, 13, 28, 29, 0, DateTimeKind.Unspecified),
                            CupCount = 1,
                            IceName = "去冰",
                            Money2 = "65",
                            Name = "沉香烏龍那提",
                            OrderName = "弟弟",
                            Shop = "波仕-鮮奶茶系列",
                            SugarName = "半糖",
                            TeaMaterialName = "椰果",
                            Total = "75"
                        },
                        new
                        {
                            OrderTime = new DateTime(2024, 2, 13, 13, 30, 31, 0, DateTimeKind.Unspecified),
                            CupCount = 1,
                            IceName = "去冰",
                            Money2 = "65",
                            Name = "沉香烏龍那提",
                            OrderName = "弟弟",
                            Shop = "波仕-鮮奶茶系列",
                            SugarName = "半糖",
                            TeaMaterialName = "椰果",
                            Total = "75"
                        },
                        new
                        {
                            OrderTime = new DateTime(2024, 5, 9, 4, 2, 17, 0, DateTimeKind.Unspecified),
                            CupCount = 1,
                            IceName = "去冰",
                            Money2 = "65",
                            Name = "沉香烏龍那提",
                            OrderName = "弟弟",
                            Shop = "波仕-鮮奶茶系列",
                            SugarName = "半糖",
                            TeaMaterialName = "椰果",
                            Total = "75"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
